'use client'
import React, { useMemo, useRef, useState } from 'react'
import { motion } from 'framer-motion'
import { Mic, Save, Loader2 } from 'lucide-react'
import { useLifeStore } from '../../lib/store'
import { BASE_URL, authHeaders } from '../../lib/api'

export default function VoiceTrainingModal({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) {
  const [phase, setPhase] = useState<1 | 2>(1)
  const [newName, setNewName] = useState('')
  const [recording, setRecording] = useState(false)
  const [processing, setProcessing] = useState(false)
  const [clips, setClips] = useState<Blob[]>([])
  const [error, setError] = useState('')
  const recorderRef = useRef<MediaRecorder | null>(null)
  const chunksRef = useRef<Blob[]>([])
  const setAiName = useLifeStore((s) => s.setAiName)
  const aiName = useLifeStore((s) => s.aiName)
  const progress = useMemo(() => Math.min(100, Math.round((clips.length / 8) * 100)), [clips.length])
  if (!isOpen) return null
  const startRecording = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const recorder = new MediaRecorder(stream); chunksRef.current = []; recorder.ondataavailable = (event) => event.data.size > 0 && chunksRef.current.push(event.data); recorder.onstop = () => { setClips((prev) => [...prev, new Blob(chunksRef.current, { type: 'audio/webm' })].slice(0, 8)); stream.getTracks().forEach((track) => track.stop()) }; recorderRef.current = recorder; recorder.start(); setRecording(true) } catch { setError('Não foi possível acessar o microfone.') } }
  const stopRecording = () => { recorderRef.current?.stop(); setRecording(false) }
  const processAndSave = async () => { setProcessing(true); setError(''); try { const formData = new FormData(); formData.append('new_name', newName); clips.slice(0, 8).forEach((clip, index) => formData.append('files', clip, `voice_${index + 1}.webm`)); const res = await fetch(`${BASE_URL}/api/v1/voice/train-wake-word`, { method: 'POST', body: formData, headers: authHeaders() }); const data = await res.json(); if (!res.ok) throw new Error(data?.detail || 'Falha ao treinar a voz'); setAiName(newName); onClose() } catch (err: any) { setError(err.message || 'Erro no treinamento') } finally { setProcessing(false) } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/70" onClick={onClose} /><motion.div initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} className="relative z-10 w-full max-w-2xl rounded-3xl border border-slate-700 bg-slate-900 p-6 shadow-2xl">{phase === 1 ? <div className="space-y-4"><h3 className="text-xl font-semibold">Como você quer me chamar?</h3><input value={newName} onChange={(e) => setNewName(e.target.value)} placeholder="Ex.: Sexta-feira" className="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3" /><button disabled={!newName.trim()} onClick={() => setPhase(2)} className="w-full rounded-xl bg-cyan-500 px-4 py-3 font-semibold text-slate-950 disabled:opacity-60">Avançar</button></div> : <div className="space-y-4"><div className="text-center"><h3 className="text-xl font-semibold">Diga &quot;{newName}&quot; (Passo {clips.length + 1} de 8)</h3><p className="text-sm text-slate-400">Repita o nome com naturalidade para calibrar a pronúncia.</p></div><div className="h-3 overflow-hidden rounded-full bg-slate-800"><div className="h-full bg-gradient-to-r from-cyan-500 to-violet-500" style={{ width: `${progress}%` }} /></div><div className="flex justify-center py-2"><motion.button onMouseDown={startRecording} onMouseUp={stopRecording} onTouchStart={startRecording} onTouchEnd={stopRecording} animate={recording ? { scale: [1, 1.08, 1] } : { scale: 1 }} transition={{ repeat: recording ? Infinity : 0, duration: 1.1 }} className={`flex h-32 w-32 items-center justify-center rounded-full border ${recording ? 'border-rose-300 bg-rose-600' : 'border-rose-300 bg-rose-500'}`}><Mic /></motion.button></div><div className="text-center text-sm text-slate-400">{recording ? 'Ouvindo...' : 'Segure para gravar e solte para salvar.'}</div>{clips.length >= 8 && <button onClick={processAndSave} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-500 px-4 py-3 font-semibold text-slate-950">{processing ? <Loader2 className="animate-spin" /> : <Save />} Processar Voz e Salvar</button>}<button onClick={() => { setPhase(1); setClips([]); setError('') }} className="w-full rounded-xl bg-slate-800 px-4 py-3">Voltar</button></div>}{error && <div className="mt-4 rounded-xl border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-sm text-rose-200">{error}</div>}<div className="mt-2 text-sm text-slate-500">Nome atual: {aiName}</div></motion.div></div>
    return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/70" onClick={onClose} /><motion.div initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} className="relative z-10 w-full max-w-2xl rounded-3xl border border-slate-700 bg-slate-900 p-6 shadow-2xl">{phase === 1 ? <div className="space-y-4"><h3 className="text-xl font-semibold">Como você quer me chamar?</h3><input value={newName} onChange={(e) => setNewName(e.target.value)} placeholder="Digite um nome" className="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3" /><button disabled={!newName.trim()} onClick={() => setPhase(2)} className="w-full rounded-xl bg-cyan-500 px-4 py-3 font-semibold text-slate-950 disabled:opacity-60">Avançar</button></div> : <div className="space-y-4"><div className="text-center"><h3 className="text-xl font-semibold">Diga &quot;{newName}&quot; (Passo {clips.length + 1} de 8)</h3><p className="text-sm text-slate-400">Repita o nome com naturalidade para calibrar a pronúncia.</p></div><div className="h-3 overflow-hidden rounded-full bg-slate-800"><div className="h-full bg-gradient-to-r from-cyan-500 to-violet-500" style={{ width: `${progress}%` }} /></div><div className="flex justify-center py-2"><motion.button onMouseDown={startRecording} onMouseUp={stopRecording} onTouchStart={startRecording} onTouchEnd={stopRecording} animate={recording ? { scale: [1, 1.08, 1] } : { scale: 1 }} transition={{ repeat: recording ? Infinity : 0, duration: 1.1 }} className={`flex h-32 w-32 items-center justify-center rounded-full border ${recording ? 'border-rose-300 bg-rose-600' : 'border-rose-300 bg-rose-500'}`}><Mic /></motion.button></div><div className="text-center text-sm text-slate-400">{recording ? 'Ouvindo...' : 'Segure para gravar e solte para salvar.'}</div>{clips.length >= 8 && <button onClick={processAndSave} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-500 px-4 py-3 font-semibold text-slate-950">{processing ? <Loader2 className="animate-spin" /> : <Save />} Processar Voz e Salvar</button>}<button onClick={() => { setPhase(1); setClips([]); setError('') }} className="w-full rounded-xl bg-slate-800 px-4 py-3">Voltar</button></div>}{error && <div className="mt-4 rounded-xl border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-sm text-rose-200">{error}</div>}<div className="mt-2 text-sm text-slate-500">Nome atual: {aiName}</div></motion.div></div>
}
